### ISSUE TITLE
Arguments with escaped space are handle as 2 arguments instead of 1

### ISSUE THREAD

**Issue by lotharthesavior** [pointybeard/php-cli-lib#1]
Hello,

First of all, thanks for this library. I just want to register a small issue here:

The php argv understands the escaped space arguments, but I noticed that when passed this lib is not accepting the 2 sides of the escaped space as 1 single argument. e.g.:

command_args.php:
```php
use CLILib\Argument;

$args = new Argument\Iterator();
//var_dump($args);
foreach ($args as $arg) {
    var_dump( $arg->name() );
    var_dump( $arg->value() );
}
```

When I run this:
```shell
php command_args.php -first interesting --second must\ have
```

This is the output:
```shell
string(5) "first"
string(11) "interesting"
string(6) "second"
string(4) "must"
```

This is the expected output:
```shell
string(5) "first"
string(11) "interesting"
string(6) "second"
string(4) "must have"
```

As I said, the global `$argv` from php gets like the expected version above. I believe that the regex code here: `https://github.com/pointybeard/php-cli-lib/blob/master/src/CLILib/Argument/Iterator.php#L37` is missing something.

Regards,
Savio Resende

**Comment by pointybeard** [comment]
Thanks Savio!

**Comment by pointybeard** [comment]
So, this package has been deprecated in favour of my helper libraries https://github.com/pointybeard/helpers, specifically https://github.com/pointybeard/helpers-cli-input

I will update the readme to reflect this.
